### PR TITLE
Resurrect support for Cabal-1.22

### PR DESCRIPTION
**Pull request by tmcdonell**
This is pretty awful, but allows the package to build with out-of-the-box GHC-7.10 again.

### CODE REVIEW

**Comment by robeverest** [comment]
Thanks!

**Comment by tmcdonell** [comment]
Did you release this on Hackage yet? Do you want me to?

**Comment by robeverest** [comment]
Not yet, no. There's no reason it can't be, though. I'll make a release now.

**Comment by robeverest** [comment]
So it turns out the Cabal woes aren't over. See [here](https://travis-ci.org/robeverest/cufft/builds/174167199). It looks like we've been using mismatching versions of `Cabal` and `cabal-install` in travis and it's worked up till now due to luck. The new version of Cabal released a few days ago finally seems to break it. 

Before I go fiddling with it, I'm not sure I understand your changes to `.travis.yml`. Is there a reason you explicitly install `Cabal >= 1.22` in travis rather than just changing the cabal versions in the matrix?

Either way, this doesn't affect the release, so I'll make that anyway.

**Comment by tmcdonell** [comment]
Ah, I noticed that these failures had started yesterday, but for some reason [this package](https://travis-ci.org/tmcdonell/nvvm) is completely fine despite being basically identical. I'll have a look at the new `cabal-install`.

`CABAL` in the build matrix is for `cabal-install`. I choose the version that would have "shipped" with that version of ghc, but I guess it is reasonable to choose `>= 1.22` for that as well (we'd still need to upgrade Cabal-the-library separately though).

**Pull request merged**
